The_Gossip_Project/config/routes.rb
Rails.application.routes.draw do

  get '/cities/show',  to: 'static_pages#show_cities', as: 'show_cities'
  get '/welcome', to: 'dynamic_pages#welcome', as: 'welcome'
  get '/show/:id', to: 'dynamic_pages#show', as: 'welcome_logged'
  get '/welcome', to: 'dynamic_pages#welcome', as: 'home'

  get '/contact', to: 'static_pages#contact'
  
  get '/team', to: 'static_pages#team'


resources :gossips, only: [:new, :create, :show, :update, :edit, :destroy]

resources :users, only: [:show]
resources :currentusers, only: [:new, :create, :show, :update, :edit, :destroy]

resources :cities, only: [:show]


end

The_Gossip_Project/app/models/gossip.rb
class Gossip < ApplicationRecord
  
  validates :title, presence: true#, format:{ with: /\A.{3,14}$\z/, message: "%{value} is not a valid title" }
  validates :content, presence: true 
  # 1-N association with users table
  belongs_to :user

  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with tags table via the gossip_meta table
  has_many :tags, through: :gossip_meta

  # 1-N polymorphic association with comments as commentable
  has_many :comments, as: :commentable

  # 1-N associations with likes
  has_many :likes
end

The_Gossip_Project/app/controllers/gossips_controller.rb
  class GossipsController < ApplicationController

  

    def new
      @gossip = Gossip.new
      end
  
    def create
      # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
      # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      
      @gossip = Gossip.new(title:params[:gossip_text], content:params[:gossip_content])# a changer quand fonction login user sera implémenté
      @gossip.user = User.find_by(id:session[:user_id])

      if @gossip.save 
      then redirect_to welcome_logged_path(id:@gossip.user.first_name)
      end

    end

    def show
      @gossip = Gossip.find(params[:id])
    end

    def edit
      @gossip =  Gossip.find(params[:id])
    end 


    def update
      @gossip = Gossip.find(params[:id])
      if @gossip.update(title: params[:gossip][:title], content: params[:gossip][:content])
      then redirect_to gossip_path(:id => @gossip.id)
      end
    end 

    def destroy
      @gossip = Gossip.find(params[:id])
      if @gossip.destroy
      then redirect_to welcome_path
      end
    end


  end

 
  

The_Gossip_Project/app/helpers/gossips_helper.rb
module GossipsHelper
end

The_Gossip_Project/app/views/gossips/edit.html.erb
<!-- ... -->
<% if @current_user %>
  <%= form_for @gossip do |f| %>
    <%= f.label 'Titre du Gossip' %><br>
    <%= f.text_field :title %><br>

    <%= f.label 'Contenu du Gossip' %><br>
    <%= f.text_area :content %><br>

    <%= f.submit "Submit Article" %>
  <% end %>

<% else %>

  <p> Merci de vous connecter </p>

<% end %>
<!-- ... -->

The_Gossip_Project/app/views/gossips/new.html.erb
    <!-- ... -->

      <% if @current_user %>
      
        <form action= <%= gossips_path %> method="POST">

        <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

        <div class="container"> 
    
        <div class="form-group row"> 
            <label class="col-sm-2 col-form-label">Rentre le titre de ton Gossip </label>
          <input class="col-2" type="text" name="gossip_text">
        </div>
    
        <div class="form-group row"> 
            <label class="col-sm-2 col-form-label">Rentre ton contenu secret </label>
          <input class="col-5" type="text" name="gossip_content">
        </div>
    
        <div class="form-group row">
          <input class="col-2" type="submit" value="Valider">
        </div>

        </form>

      <% else %>

      <p> Merci de vous connecter </p>

      <% end %>

    <!-- ... -->

The_Gossip_Project/app/views/gossips/show.html.erb
<% if @current_user %>

    <h1>Bienvenue sur la page du gossip n° <%= @gossip.id %></h1>


    <p>Gossip rédigé par : <%= @gossip.user.first_name %></p> 
    <p>Sa ville :  <%= @gossip.user.city.name%></p>
    <p>Crée le : <%= @gossip.created_at%></p>
    <p>Le titre du Gossip : <%= @gossip.title%></p>
    <p>Voici le gossip : <%= @gossip.content%></p>

    <% #redirection vers la fiche auteur du gossip %>

    <a class="nav-link" <%= link_to "Page de "+@gossip.user.first_name, user_path(:id => @gossip.user_id) %> </a>

    <% #redirection vers la fiche ville du gossip %>

    <a class="nav-link" <%= link_to "Vas vers la page de ta ville"+@gossip.user.city.name, city_path(:id => @gossip.user.city.id) %> </a>

    <% #redirection vers la page de modification du gossip %>

    <a class="nav-link" <%= link_to "Modifie ton Gossip",  edit_gossip_path(:id => @gossip.id)%> </a>

    <div class="row justify-content-center">

    <button type="button" class="btn btn-danger col-2 " data-confirm:"Souhaitez vous vraiment continuer ?"><%= link_to"Supprimer", gossip_path, method: :delete, class:"text-white" %> </button>

    </div>

<% else %>

    <p> Merci de vous connecter </p>

<% end %>