The_Gossip_Project/config/routes.rb
Rails.application.routes.draw do

  get '/cities/show',  to: 'static_pages#show_cities', as: 'show_cities'
  get '/welcome', to: 'dynamic_pages#welcome', as: 'welcome'
  get '/show/:id', to: 'dynamic_pages#show', as: 'welcome_logged'
  get '/welcome', to: 'dynamic_pages#welcome', as: 'home'

  get '/contact', to: 'static_pages#contact'
  
  get '/team', to: 'static_pages#team'


resources :gossips, only: [:new, :create, :show, :update, :edit, :destroy]

resources :users, only: [:show]
resources :currentusers, only: [:new, :create, :show, :update, :edit, :destroy]

resources :cities, only: [:show]


end

The_Gossip_Project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

The_Gossip_Project/app/models/city.rb
class City < ApplicationRecord
  # 1-N association with users table
  has_many :users
end

The_Gossip_Project/app/models/comment.rb
class Comment < ApplicationRecord
  # 1-N associations with user
  belongs_to :user

  # 1-N polymorphic association with comment and gossip
  belongs_to :commentable, polymorphic: true # can be associated to anything commentable
  has_many :comments, as: :commentable # is something commentable

  # 1-N associations with likes
  has_many :likes
end

The_Gossip_Project/app/models/gossip.rb
class Gossip < ApplicationRecord
  
  validates :title, presence: true#, format:{ with: /\A.{3,14}$\z/, message: "%{value} is not a valid title" }
  validates :content, presence: true 
  # 1-N association with users table
  belongs_to :user

  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with tags table via the gossip_meta table
  has_many :tags, through: :gossip_meta

  # 1-N polymorphic association with comments as commentable
  has_many :comments, as: :commentable

  # 1-N associations with likes
  has_many :likes
end

The_Gossip_Project/app/models/gossip_metum.rb
# the join table that maps the N-N association between gossips and tags
class GossipMetum < ApplicationRecord
  # 1-N association with gossips table
  belongs_to :gossip

  # 1-N association with tags table
  belongs_to :tag
end

The_Gossip_Project/app/models/like.rb
class Like < ApplicationRecord
  # 1-N associations with users, gossips and comments
  belongs_to :user
  # can apply to a gossip or a comment
  belongs_to :gossip, optional: true if :comment_id
  belongs_to :comment, optional: true if :gossip_id
end

The_Gossip_Project/app/models/message_delivering.rb
# the join table that maps the N-N association between recipients and received_messages
class MessageDelivering < ApplicationRecord
  # 1-N association with recipients (users) table
  # class_name tells rails recipient is a user
  belongs_to :recipient, class_name: 'User'

  # 1-N association with received_messages (private_messages) table
  # class_name tells rails received_message is a private_message
  belongs_to :received_message, class_name: 'PrivateMessage'
end

The_Gossip_Project/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  # 1-N association with senders (users) table
  belongs_to :sender, class_name: 'User'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :received_message_id

  # N-N association with recipients (users) table via message_deliverings table
  has_many :recipients, through: :message_deliverings, source: :recipient
end

The_Gossip_Project/app/models/tag.rb
class Tag < ApplicationRecord
  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with gossips table via gossips_meta table
  has_many :gossips, through: :gossip_meta
end

The_Gossip_Project/app/models/user.rb
class User < ApplicationRecord

  # adding validations
  validates :email, presence: true, uniqueness: {message: "email already subscribed"}, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :first_name, presence: true, format: { with: /\A[-'a-zA-ZÀ-ÖØ-öø-ÿ]+\z/, message: "%{value} is not a valid first name" }
  validates :last_name, presence: true, format: { with: /\A[-'a-zA-ZÀ-ÖØ-öø-ÿ]+\z/, message: "%{value} is not a valid last name" }
  validates :city, presence: true
  validates :age, presence:true, numericality: { greater_than_or_equal_to: 6, less_than: 100, message: "%{value} is not a valid age or not respecting the terms of service" }
  validates :password_digest, presence: true



  has_secure_password

  belongs_to :city
  # 1-N association with gossips table
  has_many :gossips

  # 1-N association with sent_messages (private_messages) table
  # users renamed as senders for this association, class_name explains it to Rails
  has_many :sent_messages, foreign_key: :sender_id, class_name: 'PrivateMessage'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :recipient_id

  # N-N association with received_messages (private_messages) table via the message_deliverings table
  # renamed as recipients but doesn't show here
  has_many :received_messages, through: :message_deliverings

  # 1-N associations with comments
  has_many :comments

  # 1-N associations with likes
  has_many :likes
end

The_Gossip_Project/app/controllers/cities_controller.rb
class CitiesController < ApplicationController


    def show

        @city = City.find(params[:id])
   
    end

end

The_Gossip_Project/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @city = City.find(@user.city_id)
    end 


end

The_Gossip_Project/app/helpers/application_helper.rb
module ApplicationHelper
end

The_Gossip_Project/app/helpers/cities_helper.rb
module CitiesHelper
end

The_Gossip_Project/app/helpers/current_user_helper.rb
module CurrentUserHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
    
      def logged_in?
        !session[:user_id].nil?
      end
end

The_Gossip_Project/app/helpers/currentusers_helper.rb
module CurrentusersHelper
   
end

The_Gossip_Project/app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

The_Gossip_Project/app/helpers/gossips_helper.rb
module GossipsHelper
end

The_Gossip_Project/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

The_Gossip_Project/app/helpers/users_helper.rb
module UsersHelper
end

The_Gossip_Project/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <title>GossipProjectControllerRoutesVersion</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand navbar-light bg-danger">
  <a class="navbar-brand text-white" href="#">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">

    <ul class=nav nav-pills nav-fill>
    <li class="nav-item">

      <% if @current_user %>


        <%= link_to "Acceuil", welcome_logged_path(:id => @current_user.first_name), class:"nav-link active text-white" %> 

      <% else %>

      <%= link_to "Accuil", home_path, class:"nav-link active text-white" %> 

      <% end %>
      
    </li>
    <li class="nav-item">
        <%= link_to "Team", team_path, class:"nav-link active text-white" %> 
    </li>
    <li class="nav-item">
        <%= link_to "Contact",contact_path, class:"nav-link active text-white" %> 
    </li>
    </ul>

    
      <form class="form-inline ml-auto">
      <div class="form-group mx-sm-3 mb-2">
        <input class="form-control" type="search" placeholder="Chercher" aria-label="Search">
      </div>
      <div class="form-group mx-sm-3 mb-2">
        <button class="btn btn-primary" type="submit">Recherche</button>
      </div>
     
      </form>
    

  </div>
</nav>



    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  
  <body>


    
    <%= yield %>
  </body>

  <!-- Footer -->

  <div class="navbar navbar-expand navbar-light bg-danger fixed-bottom py-3">
    <div class="col-12 bg-danger text-white">

      <div class="container text-center">

        <small>Copyright &copy; The Gossip Project</small>

    </div>
  </div>

    <!-- Footer -->

</html>