The_Gossip_Project/config/routes.rb
Rails.application.routes.draw do

  get '/cities/show',  to: 'static_pages#show_cities', as: 'show_cities'
  get '/welcome', to: 'dynamic_pages#welcome', as: 'welcome'
  get '/show/:id', to: 'dynamic_pages#show', as: 'welcome_logged'
  get '/welcome', to: 'dynamic_pages#welcome', as: 'home'

  get '/contact', to: 'static_pages#contact'
  
  get '/team', to: 'static_pages#team'


resources :gossips, only: [:new, :create, :show, :update, :edit, :destroy]

resources :users, only: [:show]
resources :currentusers, only: [:new, :create, :show, :update, :edit, :destroy]

resources :cities, only: [:show]


end

The_Gossip_Project/app/controllers/currentusers_controller.rb
class CurrentusersController < ApplicationController


    def show
    end

    def create

        
        my_user = User.find_by(email:params[:login_email]) # recherche de l'utilisateur en BDD 
        
        case my_user # case pour rediriger selon l'input user

        when nil # quand utilisateur non valide (n'existe pas en BDD)
            redirect_to new_currentuser_path #redirige formulaire d'identification
        when my_user.authenticate(params[:login_password]) # quand utlisateur correct et mot de passe correct
          then redirect_to welcome_logged_path(:id => my_user.first_name) # redirige vers bonjour prénom utlisateur
        end

        if my_user && my_user.authenticate(params[:login_password])
            session[:user_id]= my_user.id
        end
        # app/controllers/users_controller.rb

    end


    def edit
    end

    def update
    end

    def destroy
    
        reset_session
        session[:user_id] = nil         
        redirect_to welcome_path 
    end

end

The_Gossip_Project/app/helpers/current_user_helper.rb
module CurrentUserHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
    
      def logged_in?
        !session[:user_id].nil?
      end
end

The_Gossip_Project/app/helpers/currentusers_helper.rb
module CurrentusersHelper
   
end

The_Gossip_Project/app/views/currentusers/new.html.erb
<!-- ... -->

<br>
<br>
      
<form action= <%= currentusers_path %> method="POST">

<input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

<div class="container"> 

<div class="form-group row"> 
    <label class="col-sm-3 col-form-label">Ton email </label>
  <input class="col-2" type="text" name="login_email">
</div>

<div class="form-group row"> 
    <label class="col-sm-3 col-form-label">Ton mot de passe </label>
  <input class="col-2" type="text" name="login_password">
</div>

<div class="form-group row">
  <input class="col-2" type="submit" value="Log in">
</div>

</form>


<!-- ... -->