The_Gossip_Project/config/routes.rb
Rails.application.routes.draw do

  get '/cities/show',  to: 'static_pages#show_cities', as: 'show_cities'
  get '/welcome', to: 'dynamic_pages#welcome', as: 'welcome'
  get '/show/:id', to: 'dynamic_pages#show', as: 'welcome_logged'
  get '/welcome', to: 'dynamic_pages#welcome', as: 'home'

  get '/contact', to: 'static_pages#contact'
  
  get '/team', to: 'static_pages#team'


resources :gossips, only: [:new, :create, :show, :update, :edit, :destroy]

resources :users, only: [:show]
resources :currentusers, only: [:new, :create, :show, :update, :edit, :destroy]

resources :cities, only: [:show]


end

The_Gossip_Project/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

The_Gossip_Project/app/models/city.rb
class City < ApplicationRecord
  # 1-N association with users table
  has_many :users
end

The_Gossip_Project/app/models/comment.rb
class Comment < ApplicationRecord
  # 1-N associations with user
  belongs_to :user

  # 1-N polymorphic association with comment and gossip
  belongs_to :commentable, polymorphic: true # can be associated to anything commentable
  has_many :comments, as: :commentable # is something commentable

  # 1-N associations with likes
  has_many :likes
end

The_Gossip_Project/app/models/gossip.rb
class Gossip < ApplicationRecord
  
  validates :title, presence: true#, format:{ with: /\A.{3,14}$\z/, message: "%{value} is not a valid title" }
  validates :content, presence: true 
  # 1-N association with users table
  belongs_to :user

  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with tags table via the gossip_meta table
  has_many :tags, through: :gossip_meta

  # 1-N polymorphic association with comments as commentable
  has_many :comments, as: :commentable

  # 1-N associations with likes
  has_many :likes
end

The_Gossip_Project/app/models/gossip_metum.rb
# the join table that maps the N-N association between gossips and tags
class GossipMetum < ApplicationRecord
  # 1-N association with gossips table
  belongs_to :gossip

  # 1-N association with tags table
  belongs_to :tag
end

The_Gossip_Project/app/models/like.rb
class Like < ApplicationRecord
  # 1-N associations with users, gossips and comments
  belongs_to :user
  # can apply to a gossip or a comment
  belongs_to :gossip, optional: true if :comment_id
  belongs_to :comment, optional: true if :gossip_id
end

The_Gossip_Project/app/models/message_delivering.rb
# the join table that maps the N-N association between recipients and received_messages
class MessageDelivering < ApplicationRecord
  # 1-N association with recipients (users) table
  # class_name tells rails recipient is a user
  belongs_to :recipient, class_name: 'User'

  # 1-N association with received_messages (private_messages) table
  # class_name tells rails received_message is a private_message
  belongs_to :received_message, class_name: 'PrivateMessage'
end

The_Gossip_Project/app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  # 1-N association with senders (users) table
  belongs_to :sender, class_name: 'User'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :received_message_id

  # N-N association with recipients (users) table via message_deliverings table
  has_many :recipients, through: :message_deliverings, source: :recipient
end

The_Gossip_Project/app/models/tag.rb
class Tag < ApplicationRecord
  # 1-N association with gossip_meta table
  has_many :gossip_meta

  # N-N association with gossips table via gossips_meta table
  has_many :gossips, through: :gossip_meta
end

The_Gossip_Project/app/models/user.rb
class User < ApplicationRecord

  # adding validations
  validates :email, presence: true, uniqueness: {message: "email already subscribed"}, format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "email adress please" }
  validates :first_name, presence: true, format: { with: /\A[-'a-zA-ZÀ-ÖØ-öø-ÿ]+\z/, message: "%{value} is not a valid first name" }
  validates :last_name, presence: true, format: { with: /\A[-'a-zA-ZÀ-ÖØ-öø-ÿ]+\z/, message: "%{value} is not a valid last name" }
  validates :city, presence: true
  validates :age, presence:true, numericality: { greater_than_or_equal_to: 6, less_than: 100, message: "%{value} is not a valid age or not respecting the terms of service" }
  validates :password_digest, presence: true



  has_secure_password

  belongs_to :city
  # 1-N association with gossips table
  has_many :gossips

  # 1-N association with sent_messages (private_messages) table
  # users renamed as senders for this association, class_name explains it to Rails
  has_many :sent_messages, foreign_key: :sender_id, class_name: 'PrivateMessage'

  # 1-N association with message_deliverings table
  has_many :message_deliverings, foreign_key: :recipient_id

  # N-N association with received_messages (private_messages) table via the message_deliverings table
  # renamed as recipients but doesn't show here
  has_many :received_messages, through: :message_deliverings

  # 1-N associations with comments
  has_many :comments

  # 1-N associations with likes
  has_many :likes
end

The_Gossip_Project/app/controllers/cities_controller.rb
class CitiesController < ApplicationController


    def show

        @city = City.find(params[:id])
   
    end

end

The_Gossip_Project/app/controllers/dynamic_pages_controller.rb
class DynamicPagesController < ApplicationController
 
  def welcome
  	@first_name = params[:id]
  end

  def show
    @first_name = params[:id]
  end

end

The_Gossip_Project/app/controllers/gossips_controller.rb
  class GossipsController < ApplicationController

  

    def new
      @gossip = Gossip.new
      end
  
    def create
      # Méthode qui créé un potin à partir du contenu du formulaire de new.html.erb, soumis par l'utilisateur
      # pour info, le contenu de ce formulaire sera accessible dans le hash params (ton meilleur pote)
      # Une fois la création faite, on redirige généralement vers la méthode show (pour afficher le potin créé)
      
      @gossip = Gossip.new(title:params[:gossip_text], content:params[:gossip_content])# a changer quand fonction login user sera implémenté
      @gossip.user = User.find_by(id:session[:user_id])

      if @gossip.save 
      then redirect_to welcome_logged_path(id:@gossip.user.first_name)
      end

    end

    def show
      @gossip = Gossip.find(params[:id])
    end

    def edit
      @gossip =  Gossip.find(params[:id])
    end 


    def update
      @gossip = Gossip.find(params[:id])
      if @gossip.update(title: params[:gossip][:title], content: params[:gossip][:content])
      then redirect_to gossip_path(:id => @gossip.id)
      end
    end 

    def destroy
      @gossip = Gossip.find(params[:id])
      if @gossip.destroy
      then redirect_to welcome_path
      end
    end


  end

 
  

The_Gossip_Project/app/controllers/users_controller.rb
class UsersController < ApplicationController

    def show
        @user = User.find(params[:id])
        @city = City.find(@user.city_id)
    end 


end

The_Gossip_Project/app/helpers/application_helper.rb
module ApplicationHelper
end

The_Gossip_Project/app/helpers/cities_helper.rb
module CitiesHelper
end

The_Gossip_Project/app/helpers/current_user_helper.rb
module CurrentUserHelper
    def current_user
        User.find_by(id: session[:user_id])
      end
    
       def log_in(user)
        session[:user_id] = user.id
      end
    
      def logged_in?
        !session[:user_id].nil?
      end
end

The_Gossip_Project/app/helpers/currentusers_helper.rb
module CurrentusersHelper
   
end

The_Gossip_Project/app/helpers/dynamic_pages_helper.rb
module DynamicPagesHelper
end

The_Gossip_Project/app/helpers/gossips_helper.rb
module GossipsHelper
end

The_Gossip_Project/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

The_Gossip_Project/app/helpers/users_helper.rb
module UsersHelper
end

The_Gossip_Project/app/views/dynamic_pages/show.html.erb
<!-- Jumbotron-->
        
<div class="jumbotron" style="text-align: center">
    <h1 class="display-4 pt-5 font-weight-bold text-dark">Bienvenue <%= @first_name %> sur The Gossip Project</h1>
    <a class="display-4" href="gossips.jpg" style="color:rgb(255, 250, 250)" >Partez a l'aventure</a>	
    <h2 class="display-5" style="color:rgb(255, 250, 250)" >Voici tous les Gossips du moment</h2> 

        <div class="row justify-content-center">
        <button type="button" class="btn btn-danger w-25">
        <%= link_to"Se deconnecter !", currentuser_path, method: :delete, class:"text-white" %> </button>
        </div
        <div class="row justify-content-center">
        <button type="button" class="btn btn-info w-25">
        <%= link_to"Créer un Gossip signé #{@first_name}!", new_gossip_path, class:"text-white" %> </button>
        </div
</div>





<div class="card-columns">

<% Gossip.all.each do |gossip| %>  

<div class="card"> 

    <div class="card-header"

        <h4 class="card-title"> 
            <div class="d-flex justify-content-center"><%= gossip.title %> </div> <!accessing title of gossip>
        </h4>  

    </div>

    <div class="card-body">

        <p class="card-text">
            <div class="d-flex justify-content-center"> <%= gossip.user.first_name %> </div> <!accessing firstname of Author/owner of Gossip>
        </p>   

        <div class="card-footer">
            <div class="d-flex justify-content-center"> 
            <%= link_to "Voir le Gossip", gossip_path(:id => gossip.id), class: "text-decoration-none card-title" %>
            </div>
        </div>
    </div>
</div>

<% end %>

</div>

The_Gossip_Project/app/views/dynamic_pages/welcome.html.erb
        <!-- Jumbotron-->
        
	<div class="jumbotron" style="background-image: url( https://media.kasperskydaily.com/wp-content/uploads/sites/92/2016/07/06021844/social-networking-rules-featured.jpg) no-repeat background-size: 50%; text-align: center;">
		<h1 class="display-4 pt-5 font-weight-bold text-dark">Bienvenue <%= @first_name %> sur The Gossip Project</h1>
		<a class="display-4" href="gossips.jpg" style="color:rgb(255, 250, 250)" >Partez a l'aventure</a>	
        <h2 class="display-5" style="color:rgb(255, 250, 250)" >Voici tous les Gossips du moment</h2> 

            <div class="row justify-content-center">
            <button type="button" class="btn btn-info w-25"data-confirm:"Souhaitez vous vraiment continuer ?">
            <%= link_to"Connecte toi !", new_currentuser_path, class:"text-white" %> </button>
            </div
    </div>





<div class="card-columns">

<% Gossip.all.each do |gossip| %>  

    <div class="card"> 

        <div class="card-header"

            <h4 class="card-title"> 
                <div class="d-flex justify-content-center"><%= gossip.title %> </div> <!accessing title of gossip>
            </h4>  

        </div>

        <div class="card-body">

            <p class="card-text">
                <div class="d-flex justify-content-center"> <%= gossip.user.first_name %> </div> <!accessing firstname of Author/owner of Gossip>
            </p>   

            <div class="card-footer">
                <div class="d-flex justify-content-center"> 
                <%= link_to "Voir le Gossip", gossip_path(:id => gossip.id), class: "text-decoration-none card-title" %>
                </div>
            </div>
        </div>
    </div>
    
<% end %>

</div>